[workspace]
resolver="2"
members = [
	"hxcfe-sys",
	"hxcfe"
]

[workspace.dependencies]

hxcfe-sys = { version="0.1.5" }
hxcfe = { version="0.1.5" }

make-cmd = "0.1.0"
dunce = "1.0.5"
bindgen = "0.72.1"
copy_dir = "0.1.3"

[patch.crates-io]

hxcfe-sys = { path = "hxcfe-sys" }
hxcfe = { path = "hxcfe" }