[workspace]
resolver="2"
members = [
	"hxcfe-sys",
	"hxcfe"
, "hxcfe_cli"]

[workspace.dependencies]

# Workspace crates
hxcfe-sys = { version = "0.2" }
hxcfe = { version = "0.2" }

# Build dependencies
make-cmd = "0.1.0"
dunce = "1.0.5"
bindgen = "0.72.1"
copy_dir = "0.1.3"
cc = "1"
walkdir = "2"

# Runtime dependencies
enumn = "0.1.12"
once_cell = "1.18.0"
parking_lot = "0.12.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
fs-err = "3.0"

# Dev dependencies
zip = "2.2"
md5 = "0.7"
tempfile = "3.13"
assert_cmd = "2.0"
predicates = "3.0"

[patch.crates-io]

hxcfe-sys = { path = "hxcfe-sys" }
hxcfe = { path = "hxcfe" }
