[package]
name = "hxcfe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hxcfe-sys.workspace = true
enumn = "*"
once_cell = "1.18.0"
parking_lot = "*"