name: WebAssembly build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:


  build-wasm-emscripten:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    
    - name: Install Rust nightly toolchain with Emscripten target
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-unknown-emscripten
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: 'latest'
    
    - name: Verify Emscripten installation
      run: |
        emcc --version
        em++ --version
    
    - name: Build for Emscripten target
      run: |
        cargo build -p hxcfe-sys --target wasm32-unknown-emscripten --verbose
        cargo build -p hxcfe --target wasm32-unknown-emscripten --verbose
    
    - name: Build for Emscripten target (release)
      run: cargo build -p hxcfe --target wasm32-unknown-emscripten --release --verbose
