name: Windows MinGW build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows-mingw:

    runs-on: windows-latest
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Install Rust nightly toolchain (GNU)
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: cargo test --target x86_64-pc-windows-gnu --verbose 
