name: Windows MinGW build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows-mingw:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          make
          git
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Install Rust nightly toolchain (GNU)
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-pc-windows-gnu
    - name: Configure environment
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    - name: Build
      run: C:\\Users\\runneradmin\\.cargo\\bin\\cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: C:\\Users\\runneradmin\\.cargo\\bin\\cargo test --target x86_64-pc-windows-gnu --verbose 
